# Generated by Django 2.1.7 on 2019-02-17 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('locID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('temperature', models.TextField()),
                ('description', models.TextField()),
                ('icon', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'owner')},
        ),
    ]
